### ISSUE TITLE
Registration bug

### ISSUE THREAD

**Issue by michelabozza** [CodeMOOC/TreasureHuntBot#33]
When players try to register trough the registration QR code, "Treasure Hunt bot" doesn't allow the registration, going on asking which game you want to register. But no game name appears.
This doesn't happen on the Treasure Hunt admin device, where the game works properly.

ITALIAN TRANSLATION:
quando i giocatori provano a registrarsi con il codice QR di registrazione, il bot "Treasure Hunt bot"
non permette di registrarsi, continuando a chiedere a quale gioco ci si voglia registrare. Ma non appare il nome di alcun gioco.
Questo non accade nel dispositivo dell'amministratore della caccia al tesoro, dove il gioco funziona.

**Comment by LorenzCK** [comment]
È possibile che la partita creata attraverso il bot non sia ancora "attiva"? Dopo la generazione ed il trasferimento dei QR Code (come pacchetto ZIP) è necessario attivare la partita cliccando sul pulsante "activate game" (che compare subito dopo la trasmissione dei codici). Se la partita non viene attivata, i codici non dovrebbero funzionare.

Se sta provando con la partita "ProvaTreasure", creata ieri alle 09:00 circa, ho provato con [questo codice di registrazione](https://t.me/treasurehuntbot?start=reg-8-247-jcfOfVKi) e sembra funzionare correttamente.

**Comment by michelabozza** [comment]
La partita è attiva, il gioco è “HuntPressana”, #246. Sul mio dispositivo funziona tutto, il problema è con gli altri dispositivi che tentano di registrarsi. 
Il codice di registrazione è il seguente:
https://t.me/treasurehuntbot?start=reg-8-246-hTe1qkuZ


La ringrazio, 
Michela Bozza

**Comment by LorenzCK** [comment]
Mi spiace per il ritardo con cui rispondo. Ho verificato il codice e sembra funzionare correttamente: sono riuscito a registrarmi alla partita “HuntPressana” con successo. Nel sistema non ho trovato tracce di utilizzi precedente dello stesso codice: risulta che, ad oggi, soltanto lei ed io abbiamo utilizzato il codice per registrarci.
Potrebbe gentilmente inviarmi il messaggio di errore che viene visualizzato sul dispositivo dei giocatori?

**Comment by michelabozza** [comment]
Quando passo dal lettore QR a Telegram, compare il primo messaggio dell’immagine. 
Digitando /mygames mi sembra di capire che il dispositivo non si sia collegato ad alcun gioco...

**Comment by LorenzCK** [comment]
Malfunction caused by Telegram 5 for iOS that fails to process deeplinks correctly, see [Reddit thread](https://www.reddit.com/r/Telegram/comments/9l62jy/telegram_5_downgrade_to_version_4/).

**Comment by michelabozza** [comment]
Buongiorno,
non sono riuscita a risolvere il problema installando la versione precedente di Telegram perché, avendo dispositivi IOS, il procedimento sarebbe troppo complicato da fare su tutti. 
Ho ovviato al problema creando una caccia al tesoro digitale con un creatore codici QR e quiz sul coding fatti con moduli Google. Per quest’anno ci arrangiamo così, in attesa che Telegram risolva il bug ☺️
Grazie per l’aiuto!!
Michela

**Comment by LorenzCK** [comment]
Ottimo! 😊 Mi dispiace molto per il disguido, speriamo risolvano il prima possibile.
A presto, Lorenz
