### ISSUE TITLE
Resources to run game on own server

### ISSUE THREAD

**Issue by TheOnlyDGS** [CodeMOOC/TreasureHuntBot#39]
Hi guys,

If I install the treasure hunt game on my own server and 100 players play the game what kind of web hosting do I need?

Will it work with a shared web hosting like dreamhost? https://www.dreamhost.com/hosting/shared/

If not, what hosting type will be required? 

Thank you,
Dipankar

**Comment by LorenzCK** [comment]
Hello Dipankar, sorry for the delay.
Do you mean 100 individual teams? If you have 100 participants but they are subdivided in teams, only the team “leaders” (the ones talking to the bot via Telegram) will be interacting with the server, so the load will be lighter.
However, a minimal shared host should be enough: our most intense games did run on a very basic server with 2 GB of RAM and 2 CPUs and the was almost no noticeable load, so I think you should be fine.

Let me know how it goes or if you have issues with the game. :)

**Comment by TheOnlyDGS** [comment]
> Hello Dipankar, sorry for the delay. Do you mean 100 individual teams? If you have 100 participants but they are subdivided in teams, only the team “leaders” (the ones talking to the bot via Telegram) will be interacting with the server, so the load will be lighter. However, a minimal shared host should be enough: our most intense games did run on a very basic server with 2 GB of RAM and 2 CPUs and the was almost no noticeable load, so I think you should be fine.
> 
> Let me know how it goes or if you have issues with the game. :)

Thank you for replying. I really appreciate it!

Yes, I mean 100 individual teams. How many teams did your most intense games have?

**Comment by LorenzCK** [comment]
I just checked and our largest game had 203 individual teams in total (I'm not entirely sure all of them played and did so concurrently, but the majority did).

**Comment by TheOnlyDGS** [comment]
> I just checked and our largest game had 203 individual teams in total (I'm not entirely sure all of them played and did so concurrently, but the majority did).

Thank you so much for taking the time to reply.

**Comment by LorenzCK** [comment]
You’re welcome! Feel free to reopen the issue if you have scaling issues or feedback on this. 😊 Cheers!
